rootProject.name = 'vault-aot-poc'

include 'startup-timing'
include '01-aot-breakage'
include '02-baseline-no-aot'
include '03-vault-with-file-secrets-and-aot'
include '04-vault-agent-and-aot'
include 'mongo-common'
include '05-mongo-baseline:sync'
include '05-mongo-baseline:reactive'
include '06-mongo-optimized:files'
include '06-mongo-optimized:agent'
